---
- name: Install blockchain backends and tunnel to a secure proxy
  hosts: blockchain
  remote_user: ubuntu
  become: yes
  become_method: sudo

  vars:
    geth_user: ubuntu
    geth_testnet: true
    geth_cache: 512
    #geth_port: 30304
    geth_datadir: "/home/{{ geth_user }}/blockchains/geth/testnet"
    geth_rpc: true
    #geth_rpcpublic: true
    #geth_rpcaddr: 0.0.0.0
    #geth_rpcport: 8080
    geth_rpcapi: "personal,eth,net,web3,admin"
    geth_rpccorsdomain: "*"
    geth_rpcvhosts: "*"
    parity_version: "1.11.4"
    networks:
      - "mainnet"
      - "ropsten"
      - "mainnet-archive"
    blockchain_apps:
      - "parity"
      - "parity-archive"
      - "geth"

  roles:
    - blockchain
