---
- name: Install blockchain backends and tunnel to a secure proxy
  hosts: blockchain
  become: yes
  become_method: sudo

  # for vars, refer to roles/blockchain/defaults/main.yml

  roles:
    - geerlingguy.munin
    - blockchain
