---
- name: Install blockchain backends and tunnel to a secure proxy
  hosts: blockchain
  remote_user: ubuntu
  become: yes
  become_method: sudo

  vars:
    geth_user: ubuntu
    geth_testnet: true
    geth_cache: 512
    #geth_port: 30304
    geth_datadir: "/home/{{ geth_user }}/blockchains/geth/testnet"
    geth_rpc: true
    #geth_rpcpublic: true
    #geth_rpcaddr: 0.0.0.0
    #geth_rpcport: 8080
    geth_rpcapi: "eth,net,web3"
    geth_rpccorsdomain: "*"
    geth_rpcvhosts: "*"
    parity_version: "1.11.4"
    blockchain_apps:
      - { name: "geth", ws_sport: "0", ws_dport: "0", sport: "8545", dport: "8555", network: "ropsten", p2p: "30303", ssh_hostname: "eth.quantstamp.com" }
      - { name: "parity", ws_sport: "8548", ws_dport: "8546", sport: "8547", dport: "8545", network: "mainnet", p2p: "30304", ssh_hostname: "rpc.blockchaindevlabs.com"}
      - { name: "parity-archive", ws_sport: "0", ws_dport: "0", sport: "8546", dport: "8557", network: "mainnet-archive", p2p: "30305", ssh_hostname: "rpc.blockchaindevlabs.com"}
    ssh_tunnels:
      - { name: "geth", sport: "8545", dport: "8555", network: "ropsten", ssh_hostname: "eth.quantstamp.com" }
      - { name: "parity", sport: "8547", dport: "8545", network: "mainnet", ssh_hostname: "rpc.blockchaindevlabs.com"}
      - { name: "parity-ws", sport: "8548", dport: "8546", network: "mainnet", ssh_hostname: "rpc.blockchaindevlabs.com"}
      - { name: "parity-archive", sport: "8546", dport: "8557", network: "mainnet-archive", ssh_hostname: "rpc.blockchaindevlabs.com"}
    private_key_name: "geth-http"
    ssh_hostname: "eth.quantstamp.com"

  roles:
    - blockchain
