---
- name: Install blockchain backends and tunnel to a secure proxy
  hosts: blockchain
  become: yes
  become_method: sudo

  vars:
    proxy_hostname: rpc.blockchaindevlabs.com
    geth_user: ubuntu
    geth_testnet: true
    geth_cache: 2048
    #geth_port: 30304
    config_lvm: true
    data_disk: "/dev/xvdg"
    base_path: "/home/{{ geth_user }}/blockchains"
    geth_rpc: true
    #geth_rpcpublic: true
    #geth_rpcaddr: 0.0.0.0
    geth_rpcapi: "eth,net,web3"
    geth_rpccorsdomain: "*"
    geth_rpcvhosts: "*"
    parity_version: "1.11.4"
    blockchain_apps:
      - { name: "geth", ws_sport: "8546", sport: "8545", network: "ropsten", p2p: "30303", enabled: true }
      - { name: "parity", ws_sport: "8548", sport: "8547", network: "mainnet", p2p: "30304", enabled: false }
      - { name: "parity-archive", ws_sport: "8548", sport: "8547", network: "mainnet", p2p: "30305", enabled: false }
    ssh_tunnels:
      - { name: "geth", sport: "8545", dport: "8545", network: "ropsten", ssh_hostname: "{{ proxy_hostname }}" }
      - { name: "geth-ws", sport: "8546", dport: "8546", network: "ropsten", ssh_hostname: "{{ proxy_hostname }}" }
      - { name: "parity", sport: "8547", dport: "8547", network: "mainnet", ssh_hostname: "{{ proxy_hostname }}"}
      - { name: "parity-ws", sport: "8548", dport: "8548", network: "mainnet", ssh_hostname: "{{ proxy_hostname }}"}
    private_key_name: "geth-http"
    tunnel_user: ubuntu

  roles:
    - blockchain
