---
- name: Install a full ethereum RPC proxy with SSL and token auth
  hosts: proxy
  remote_user: ubuntu
  become: yes
  become_method: sudo

  # for vars, refer to roles/ethrouter/defaults/main.yml

  roles:
    - ethrouter
    - geerlingguy.certbot
