---
# geth time!
- name: Add go-ethereum PPA
  apt_repository:
    #repo: deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu artful main
    repo: ppa:ethereum/ethereum
    state: present
    filename: go-ethereum

- name: Install ethereum package
  apt:
    pkg: ethereum
    state: present
    update_cache: true

# should probably put something here about creating the data directory if it is not present

- name: Install geth systemd service
  template:
    src: geth.service
    dest: /lib/systemd/system/geth.service
    owner: root
    group: root
    mode: 0644

- name: Start geth systemd service
  systemd: 
    daemon_reload: yes
    state: started
    enabled: true
    name: geth.service

# Parity time!
- name: Install Parity package
  apt:
    deb: "https://releases.parity.io/v{{ parity_version }}/x86_64-unknown-linux-gnu/parity_{{ parity_version}}_ubuntu_amd64.deb"
    state: present
    update_cache: true

- name: Install parity systemd service
  template:
    src: parity.service
    dest: /lib/systemd/system/parity.service
    owner: root
    group: root
    mode: 0644

- name: Start parity systemd service
  systemd: 
    daemon_reload: yes
    state: started
    enabled: true
    name: parity.service
