---
- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true

- name: Copy configuration for Nginx proxy
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: Restart Nginx

# this is most likely obsolete by the certbot role but keeping it here for now
#- name: Start SSL Challenge
#  letsencrypt:
#    account_key: /etc/ssl/private/eth.quantstamp.com.key
#    csr: /tmp/eth.quantstamp.com.csr
#    dest: /etc/nginx/ssl/eth.quantstamp.com.crt
#  register: eth_quantstamp_com_challenge

#- name: Copy challenge data to www server
#  copy:
#    dest: /var/www/html/{{ eth_quantstamp_com_challenge['challenge_data']['sample.com']['http-01']['resource'] }}
#    content: "{{ eth_quantstamp_com_challenge['challenge_data']['sample.com']['http-01']['resource_value'] }}"
#    when: eth_quantstamp_com_challenge|changed

#- name: Verify SSL Challenge
#  letsencrypt:
#    account_key: /etc/ssl/private/eth.quantstamp.com.key
#    csr: /tmp/eth.quantstamp.com.csr
#    dest: /etc/nginx/ssl/eth.quantstamp.com.crt
#    data: "{{ eth_quantstamp_com_challenge }}"
