---
- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true

- name: Copy configuration for Nginx proxy
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: Restart Nginx
